import type { Metadata } from "next";

import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import AuthContextProvider from "@/context/AuthContext";
import MessagesContextProvider from "@/context/MessagesContext";

export const metadata: Metadata = {
  title: "home page",
  description: "Generated by create next app",
};

type RootLayoutType = {
  children: React.ReactNode;
};

export default async function RootLayout({ children }: RootLayoutType) {
  return (
    <html lang="en">
      <body className="flex flex-col justify-between h-screen">
        <AuthContextProvider>
          <MessagesContextProvider>
            <Header />
            <div className=" flex-1 bg-black container mx-auto pt-10 px-2">
              <main className="flex-1">{children}</main>
            </div>
            <Footer />
          </MessagesContextProvider>
        </AuthContextProvider>
      </body>
    </html>
  );
}
